### ISSUE TITLE
Ошибка  Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes

### ISSUE THREAD

**Issue by llotar** [TinkoffCreditSystems/invest-openapi#139]
Добрый день,
Получаю ошибку
Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Invalid token scopes (ffd122a2102e5e06).
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<HandleResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<SendGetRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Context.<PortfolioAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

при "быстром старте":

       ```

           // токен аутентификации
            var token = "код для песочницы из личного кабинета";
            // для работы в песочнице используйте GetSandboxConnection
            var connection = ConnectionFactory.GetConnection(token);
            var context = connection.Context;

            // вся работа происходит асинхронно через объект контекста
            Portfolio portfolio;
            try
            {
                portfolio = await context.PortfolioAsync();
            }
            catch (Exception ex)
            {

                throw;
            }
```

Что я делаю не так?
Спасибо!

**Comment by llotar** [comment]
Поторопился, оказывается надо делать вот так для sandbox
            var connection = ConnectionFactory.GetSandboxConnection(token);
            var context = connection.Context;
            await context.RegisterAsync();
