### ISSUE TITLE
Бесконечное восстановление Streaming API клиента

### ISSUE THREAD

**Issue by redfoos** [TinkoffCreditSystems/invest-openapi#140]
Добрый день, а подскажите, пожалуйста, я пытаюсь подключиться с некорректным токеном, получаю соотв. ошибку, закрываю OpenApi объект, но почему-то дальше начинается бесконечная попытка что-то восстановить:

> У клиента #3 активно 0 подписок
Что-то произошло в Streaming API клиенте #4
java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:157) ~[okhttp-3.14.7.jar:na]
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:204) ~[okhttp-3.14.7.jar:na]
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:144) ~[okhttp-3.14.7.jar:na]
	at okhttp3.RealCall.enqueue(RealCall.java:93) ~[okhttp-3.14.7.jar:na]
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:190) ~[okhttp-3.14.7.jar:na]
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:409) ~[okhttp-3.14.7.jar:na]
	at ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl.restore(StreamingContextImpl.java:301) ~[openapi-java-sdk-java8-0.4.1.jar:na]
	at ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener.onFailure(StreamingContextImpl.java:372) ~[openapi-java-sdk-java8-0.4.1.jar:na]
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570) ~[okhttp-3.14.7.jar:na]
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199) ~[okhttp-3.14.7.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.7.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.7.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@25a9b823 rejected from java.util.concurrent.ThreadPoolExecutor@11c1a6f4[Shutting down, pool size = 6, active threads = 6, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355) ~[na:na]
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:154) ~[okhttp-3.14.7.jar:na]
	... 14 common frames omitted

Что это такое и как с этим быть?

**Comment by zlumyo** [comment]
Это попытки восстановление подключения к Streaming API.
По хорошему этот вопрос больше подходит для [репозитория Java SDK](https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk).

**Comment by redfoos** [comment]
@zlumyo. здравствуйте, спасибо за ответ!
А вы не могли бы связаться с коллегами или пригласить кого-нибудь сюда чтобы не создавать новое issue? Плюс, есть опасения, что там мне точно никто не ответит.

**Comment by NikitaMelnikov** [comment]
@zlumyo как раз занимается java-sdk :)
