### ISSUE TITLE
Ошибка при получении портфеля

### ISSUE THREAD

**Issue by cia76** [TinkoffCreditSystems/invest-openapi#151]
Время от времени при получении портфеля получаю ошибку. C# SDK брал через nuget. Вот подробности:

```
System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<HandleResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<SendGetRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Context.<PortfolioAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at WLDAutoTrading.Tinkoff.TFProvider.UpdateAccounts()
   at WLDAutoTrading.Manager.WLProvider.UpdateTask()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<HandleResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.<SendGetRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tinkoff.Trading.OpenApi.Network.Context.<PortfolioAsync>d__8.MoveNext()<---
```

**Comment by cia76** [comment]
По характеру ошибки, есть вариант, что были отключены серверы. Возможно, на профилактику. Запрос ушел, но ответ пришел такой, который не может разобрать Json. Я поставил try - catch и запись ошибок в лог на все вызовы Tinkoff Api. Если что поймаю, дополню здесь.

**Comment by NikitaMelnikov** [comment]
При сильном превышении лимитов https://tinkoffcreditsystems.github.io/invest-openapi/rest/ происходит блокировка по IP

**Comment by cia76** [comment]
В режиме ожидания у меня уходит 1 запрос в 1 минуту. Других запросов нет. Не думаю, что здесь блокировка по IP

**Comment by NikitaMelnikov** [comment]
Могли бы предоставить логи запросов / ответов с временем? Желательно через чат с поддержкой, будем разбираться в чем дело

**Comment by cia76** [comment]
Посмотрел вчерашний лог. Да, подобная ошибка возникает, когда (пере)запускается система автоторговли. Когда сразу запрашиваются счета, открытые позиции, новые бары. Возможно, в этот момент нагрузка становится критической, и я получаю этот ответ. На текущий момент вопрос решен.
