### ISSUE TITLE
Не работает пример генерации клиента

### ISSUE THREAD

**Issue by yutkin** [TinkoffCreditSystems/invest-openapi#5]
Пример из src/docs/rest.md:

```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:3.0.10 generate \
    -i https://api-invest.tinkoff.ru/openapi/docs/swagger-ui/swagger.yaml \
    -l go \
    -o /local/out/go
```

Падает с:
```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:3.0.10 generate \
    -i https://api-invest.tinkoff.ru/openapi/docs/swagger-ui/swagger.yaml \
    -l go \
    -o /local/out/go
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name go Available: aspnetcore
csharp
csharp-dotnet2
dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
spring
nodejs-server
openapi
openapi-yaml
kotlin-client
kotlin-server
php
python
python-flask
scala
scala-akka-http-server
swift3
swift4
typescript-angular

	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.main(SwaggerCodegen.java:96)
Caused by: java.lang.ClassNotFoundException: go
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
```

**Comment by NikitaMelnikov** [comment]
Поправим пример, спасибо

**Comment by doroginin** [comment]
А еще у вас `swagger.yaml` переехал на другой адрес: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/swagger.yaml

**Comment by NikitaMelnikov** [comment]
Мы сделали редирект с `api-invest/openapi/docs` на `https://tinkoffcreditsystems.github.io/invest-openapi/`
