### ISSUE TITLE
Не получается получить список исторических свечей

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#571]
При попытке получить свечи за интервал, падает исключение. Происходит постоянно. Зафиксировано 27 и 28 июля.

Вызов метода:

`api.getMarketContext().getMarketCandles()`

Сам стектрейс:

`com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 0]
	at com.example.trader.util.FutureUtils.getByTimeOut(FutureUtils.java:18)
	at com.example.trader.util.FutureUtils.getByTimeOut(FutureUtils.java:11)
	at com.example.trader.service.candle.impl.CandleServiceImpl.getHistoricalCandles(CandleServiceImpl.java:71)
	at com.example.trader.service.candle.impl.CandleServiceImpl.getCandlesSortedByTime(CandleServiceImpl.java:48)
	at com.example.trader.service.strategy.impl.StrategyOnTheSharpDropInLateTradingService.getOpenPosition(StrategyOnTheSharpDropInLateTradingService.java:61)
	at com.example.trader.service.position.impl.OpenPositionByOneServiceImpl.run(OpenPositionByOneServiceImpl.java:41)
	at com.example.trader.service.position.impl.OpenPositionByOneServiceImpl$$FastClassBySpringCGLIB$$7cdb984a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.example.trader.service.position.impl.OpenPositionByOneServiceImpl$$EnhancerBySpringCGLIB$$c67ec17a.run(<generated>)
	at com.example.trader.service.position.impl.OpenPositionServiceImpl.run(OpenPositionServiceImpl.java:78)
	at com.example.trader.service.scheduler.impl.OpenPositionSchedulerImpl.run(OpenPositionSchedulerImpl.java:20)
	at jdk.internal.reflect.GeneratedMethodAccessor368.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 0]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at com.example.trader.util.FutureUtils.getByTimeOut(FutureUtils.java:16)
	... 29 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3250)
	at ru.tinkoff.invest.openapi.okhttp.BaseContextImpl.handleResponse(BaseContextImpl.java:74)
	at ru.tinkoff.invest.openapi.okhttp.MarketContextImpl$10.onResponse(MarketContextImpl.java:247)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	... 3 common frames omitted
`

**Comment by AlexanderVolkovTCS** [comment]
Видимо, это дело в парсинге ответа сервера в условиях, когда сервер возвращает пустое тело ответа. Проблема конкретного SDK, перевожу вопрос туда.
